### ISSUE TITLE
Function name of gbvs

### ISSUE THREAD

**Issue by AraragiHoozuki** [super-continent/bbscript#32]
Is there any plan to update function names of gbvs.ron?
If I want to figure out it by my self, is there any tutorial?

**Comment by super-continent** [comment]
i'm currently busy and not interested in gbvs in particular (great game, but im waiting on the rollback to do anything new for it) to keep working on the config for it, however i think most people would be able to figure out the instructions if they put some time and effort into it. there isn't a tutorial for this, but the process is pretty simple and mostly reliant on your own ability to intuit what the behavior of the instruction is by messing around with it and observing what happens. here's my process:

1. identify a function that looks interesting
2. use the context the function is in, and its arguments to get a better guess at what it might be, for example reading any strings and trying to figure out what they might relate to
3. keep changing arguments to the function, set numbers to be really big, really small, 0, negative, anything like that, then test the rebuilt script in game and see what happens when you activate it (should be reliably activated by just performing the move, or moving the call to an easily accessible part of some other state, like a jab)

once you have a good idea of what it is, just add a new entry into the config file with all the regular fields entered, and you will be able to parse the built script into text containing the function name, any new argument types, etc. if your new config looks good, you can submit a PR here and i'll merge it into the main branch if it looks good and has the correct formatting, naming conventions, etc.
